services:
  - type: web
    name: cotton-disease-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && python main.py