services:
  - type: web
    name: cotton-disease-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: python api/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10